## Q1
#### Problem-1 : Terror Attack City
Problem Statement :
The Most Dangerous city in Jammu and Kashmir and the terrorist group which is most active in that city?
Print count of number of attacks in that city as integer value.
Note:Ignoring the Unknown Terrorist Group.Here Dangerous related with the number of terrorist attacks.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('terrorismData.csv')

In [4]:
df.describe()

,Year,Month,Day,Latitude,Longitude,Killed,Wounded
count,181691.000000,181691.000000,181691.000000,177135.000000,1.771340e+05,171378.000000,165380.000000
mean,2002.638997,6.467277,15.505644,23.498343,-4.586957e+02,2.403272,3.167668
std,13.259430,3.388303,8.814045,18.569242,2.047790e+05,11.545741,35.949392
min,1970.000000,0.000000,0.000000,-53.154613,-8.618590e+07,0.000000,0.000000
25%,1991.000000,4.000000,8.000000,11.510046,4.545640e+00,0.000000,0.000000
50%,2009.000000,6.000000,15.000000,31.467463,4.324651e+01,0.000000,0.000000
75%,2014.000000,9.000000,23.000000,34.685087,6.871033e+01,2.000000,2.000000
max,2017.000000,12.000000,31.000000,74.633553,1.793667e+02,1570.000000,8191.000000

In [5]:
df.shape

(181691, 17)

In [6]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [27]:
df1 = df[df.State=='Jammu and Kashmir']
print("Shape: ",df1.shape)
df1

Shape:  (2454, 17)

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
21744,1984,4,17,India,Jammu and Kashmir,South Asia,Bhela,33.315527,74.622476,Assassination,2.0,0.0,Gurbachan Singh Sandhar (Sikh lawyer) and wife,NaN,Sikh Extremists,Private Citizens & Property,Unknown
22108,1984,5,20,India,Jammu and Kashmir,South Asia,Jammu,32.726602,74.857026,Bombing/Explosion,1.0,0.0,bridge over a stream,NaN,Unknown,Transportation,Explosives
29677,1986,12,11,India,Jammu and Kashmir,South Asia,Madora,33.934929,75.154160,Bombing/Explosion,1.0,5.0,general post office complex,NaN,Unknown,Government (General),Unknown
33202,1988,1,21,India,Jammu and Kashmir,South Asia,Mand,32.888165,74.985168,Armed Assault,2.0,0.0,police unit,NaN,Unknown,Police,Firearms
33372,1988,2,7,India,Jammu and Kashmir,South Asia,Kherawali,32.523889,74.974444,Armed Assault,4.0,5.0,marriage reception,NaN,Sikh Extremists,Private Citizens & Property,Firearms
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181222,2017,12,11,India,Jammu and Kashmir,South Asia,Kralcheck Keller,33.732981,74.855559,Armed Assault,2.0,1.0,Van,12/11/2017: Assailants opened fire on a Jammu ...,Jaish-e-Mohammad (JeM),Business,Firearms
181396,2017,12,18,India,Jammu and Kashmir,South Asia,Baramulla district,34.191218,74.350010,Bombing/Explosion,0.0,0.0,Police Station,12/18/2017: Assailants threw a grenade at a po...,Unknown,Police,Explosives
181414,2017,12,19,India,Jammu and Kashmir,South Asia,Pulwama district,33.873538,74.899019,Bombing/Explosion,0.0,0.0,Police Line,12/19/2017: Assailants fired a rifle grenade a...,Unknown,Police,Explosives
181476,2017,12,22,India,Jammu and Kashmir,South Asia,Srinagar,34.083740,74.789902,Armed Assault,0.0,0.0,Post,12/22/2017: Assailants threw two petrol bombs ...,Unknown,Police,Incendiary
181672,2017,12,31,India,Jammu and Kashmir,South Asia,Lethapora,33.966527,74.964225,Armed Assault,8.0,3.0,Camp,12/31/2017: Assailants armed with grenades and...,Jaish-e-Mohammad (JeM),Police,Explosives

In [67]:
df_list = df1['City'].value_counts()
city = df_list.index[0]
attacks = df_list.values[0]
print("Most Dangerous City: ", city)
print("No of attacks: ",attacks)

df2=df1[df1.City==city]
df2['Group'].value_counts()

terroristGroup = df2['Group'].value_counts().index[1]
print("Most active terror group:" , terroristGroup)

Most Dangerous City:  Srinagar
No of attacks:  657
Most active terror group: Muslim Separatists

## Q2

#### Problem-2 : Terror Attack
Problem Statement :
Find out the Country with Highest Number of Terror Attack and in which year the most number of terrorist attack happened in that country ?
Print count of terror attacks as integer value.

In [70]:
import pandas as pd
df= pd.read_csv('terrorismData.csv')
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [77]:
country = df['Country'].value_counts().index[0]
print('Country with highest number of terrorist attacks: ', country)

Country with highest number of terrorist attacks:  Iraq

In [82]:
df1 = df[df.Country==country]
year = df1.Year.value_counts().index[0]
print("Year in which most attack happended: ", year)

Year in which most attack happended:  2014

In [83]:
print('Country with highest number of terrorist attacks: ', country)
print("Year in which most attack happended: ", year)

Country with highest number of terrorist attacks:  Iraq
Year in which most attack happended:  2014

## Q3
#### Problem-3 : Terror DeadliestAttack
Problem Statement :
Most Deadliest attack in a history of HumanKind?
Print count of Killed people as integer value.
Note: Here Deadliest attack means, in which the most number of people killed.

In [84]:
df.shape

(181691, 17)

In [85]:
df.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary

In [94]:
maxKilled = df.Killed.max()
maxKilled

1570.0

In [113]:
df1=df[df.Killed == maxKilled]
mx_killed = df1.Killed.iloc[0]
country = df1.Country.iloc[0]
group = df1.Group.iloc[0]
print(int(mx_killed), country, group)

1570 Iraq Islamic State of Iraq and the Levant (ISIL)

## Q4

In [114]:
df

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
0,1970,7,2,Dominican Republic,NaN,Central America & Caribbean,Santo Domingo,18.456792,-69.951164,Assassination,1.0,0.0,Julio Guzman,NaN,MANO-D,Private Citizens & Property,Unknown
1,1970,0,0,Mexico,Federal,North America,Mexico city,19.371887,-99.086624,Hostage Taking (Kidnapping),0.0,0.0,"Nadine Chaval, daughter",NaN,23rd of September Communist League,Government (Diplomatic),Unknown
2,1970,1,0,Philippines,Tarlac,Southeast Asia,Unknown,15.478598,120.599741,Assassination,1.0,0.0,Employee,NaN,Unknown,Journalists & Media,Unknown
3,1970,1,0,Greece,Attica,Western Europe,Athens,37.997490,23.762728,Bombing/Explosion,NaN,NaN,U.S. Embassy,NaN,Unknown,Government (Diplomatic),Explosives
4,1970,1,0,Japan,Fukouka,East Asia,Fukouka,33.580412,130.396361,Facility/Infrastructure Attack,NaN,NaN,U.S. Consulate,NaN,Unknown,Government (Diplomatic),Incendiary
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,12,31,Somalia,Middle Shebelle,Sub-Saharan Africa,Ceelka Geelow,2.359673,45.385034,Armed Assault,1.0,2.0,Checkpoint,12/31/2017: Assailants opened fire on a Somali...,Al-Shabaab,Military,Firearms
181687,2017,12,31,Syria,Lattakia,Middle East & North Africa,Jableh,35.407278,35.942679,Bombing/Explosion,2.0,7.0,Hmeymim Air Base,12/31/2017: Assailants launched mortars at the...,Muslim extremists,Military,Explosives
181688,2017,12,31,Philippines,Maguindanao,Southeast Asia,Kubentog,6.900742,124.437908,Facility/Infrastructure Attack,0.0,0.0,Houses,12/31/2017: Assailants set fire to houses in K...,Bangsamoro Islamic Freedom Movement (BIFM),Private Citizens & Property,Incendiary
181689,2017,12,31,India,Manipur,South Asia,Imphal,24.798346,93.940430,Bombing/Explosion,0.0,0.0,Office,12/31/2017: Assailants threw a grenade at a Fo...,Unknown,Government (General),Explosives
181690,2017,12,31,Philippines,Maguindanao,Southeast Asia,Cotabato City,7.209594,124.241966,Bombing/Explosion,0.0,0.0,Unknown,12/31/2017: An explosive device was discovered...,Unknown,Unknown,Explosives

In [120]:
df1 = df[df.Year>=2014]
df1.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
125335,2014,1,1,Colombia,Norte de Santander,South America,Convencion,8.868790,-73.194094,Bombing/Explosion,0.0,0.0,Crude Oil Holding Pools,01/01/2014: Assailants detonated an explosive ...,National Liberation Army of Colombia (ELN),Utilities,Explosives
125336,2014,1,1,Somalia,Banaadir,Sub-Saharan Africa,Mogadishu,2.059819,45.326115,Bombing/Explosion,4.0,20.0,Hotel,01/01/2014: A suicide bomber detonated an expl...,Al-Shabaab,Business,Explosives
125337,2014,1,1,Pakistan,Balochistan,South Asia,Quetta,30.200819,66.994354,Bombing/Explosion,3.0,31.0,Shia Pilgrims,01/01/2014: A suicide bomber crashed an explos...,Jaish-e-Islam,Private Citizens & Property,Explosives
125338,2014,1,1,Pakistan,Balochistan,South Asia,Dera Bugti,29.034412,69.158661,Bombing/Explosion,0.0,0.0,Unknown,01/01/2014: A land mine was found and defused ...,Unknown,Unknown,Explosives
125339,2014,1,1,Somalia,Middle Juba,Sub-Saharan Africa,Buale,1.097128,42.598368,Hostage Taking (Kidnapping),NaN,NaN,Aid Workers,01/01/2014: Assailants abducted ten individual...,Al-Shabaab,NGO,Unknown

In [123]:
df2 = df1[df1.Month>=5]
df2.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
127864,2014,5,24,Thailand,Pattani,Southeast Asia,Sabarang,6.867859,101.252068,Bombing/Explosion,1.0,5.0,Store,05/24/2014: An explosive device detonated outs...,Separatists,Business,Explosives
127865,2014,5,24,Thailand,Pattani,Southeast Asia,Paka Harang,6.867859,101.252068,Bombing/Explosion,1.0,5.0,Store,05/24/2014: An explosive device detonated outs...,Separatists,Business,Explosives
127866,2014,5,24,Thailand,Pattani,Southeast Asia,Paka Harang,6.867859,101.252068,Bombing/Explosion,1.0,5.0,Store,05/24/2014: An explosive device detonated outs...,Separatists,Business,Explosives
127867,2014,5,24,Thailand,Pattani,Southeast Asia,Sabarang,6.867859,101.252068,Bombing/Explosion,0.0,5.0,Store,05/24/2014: An explosive device detonated outs...,Separatists,Business,Explosives
127868,2014,5,24,Thailand,Pattani,Southeast Asia,Rusa Milae,6.873954,101.234711,Bombing/Explosion,0.0,5.0,Store,05/24/2014: An explosive device detonated outs...,Separatists,Business,Explosives

In [124]:
df3 = df2[df2.Day>=26]
df3.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
132357,2014,5,26,Kenya,Lamu,Sub-Saharan Africa,Lamu,-2.256599,40.908075,Armed Assault,3.0,1.0,Convoy,05/26/2014: Assailants opened fire on a Kenya ...,Al-Shabaab,Military,Firearms
132450,2014,5,26,Libya,Benghazi,Middle East & North Africa,Benghazi,32.069286,20.151144,Assassination,1.0,0.0,Chief Editor: Muftah Awad Bouzid,05/26/2014: Assailants opened fire on Muftah A...,Muslim extremists,Journalists & Media,Firearms
132451,2014,5,26,Libya,Benghazi,Middle East & North Africa,Benghazi,32.094952,20.268871,Bombing/Explosion,0.0,0.0,Airport,05/26/2014: Assailants fired multiple rockets ...,Unknown,Airports & Aircraft,Explosives
132452,2014,5,26,Yemen,Marib,Middle East & North Africa,Sirwah district,15.459390,45.023548,Hostage Taking (Kidnapping),0.0,0.0,Academics,05/26/2014: Assailants kidnapped six academics...,Tribesmen,Educational Institution,Unknown
132453,2014,5,26,Pakistan,Balochistan,South Asia,Kalat,29.047852,66.593323,Bombing/Explosion,0.0,0.0,Police Line,05/26/2014: An explosives-laden motorcycle det...,Unknown,Police,Explosives

In [140]:
df4 = df3[df3.Country=='India']
df4.head()

,Year,Month,Day,Country,State,Region,City,Latitude,Longitude,AttackType,Killed,Wounded,Target,Summary,Group,Target_type,Weapon_type
132468,2014,5,26,India,Andhra Pradesh,South Asia,Bandlapalli,14.714739,77.810281,Bombing/Explosion,0.0,0.0,Party Supporter,05/26/2014: An explosive device was discovered...,Unknown,Private Citizens & Property,Explosives
132496,2014,5,26,India,West Bengal,South Asia,Sandeshkhali,22.356709,88.881991,Armed Assault,0.0,12.0,Party Workers,05/26/2014: Assailants opened fire on Bharatiy...,Unknown,Violent Political Party,Firearms
132502,2014,5,26,India,West Bengal,South Asia,Sandeshkhali,22.363882,88.878679,Armed Assault,0.0,11.0,Members,05/26/2014: Assailants opened fire and threw e...,Unknown,Violent Political Party,Explosives
132526,2014,5,27,India,Jammu and Kashmir,South Asia,Khour,32.601778,74.809414,Bombing/Explosion,0.0,0.0,Unknown,05/27/2014: An explosive device was discovered...,Unknown,Unknown,Explosives
132555,2014,5,27,India,Odisha,South Asia,Bikrampur,22.338542,86.178146,Assassination,1.0,0.0,Journalist: Tarun Kumar Acharya,05/27/2014: Assailants stabbed and killed Taru...,Unknown,Journalists & Media,Melee

In [127]:
df4.shape[0]

478

In [138]:
df4['Group'].value_counts().index[1]

'Maoists'

In [137]:
print(df4.shape[0], df4['Group'].value_counts().index[1])

478 Maoists

## Q5
Problem-5 : Terror Frequency
Problem Statement :
Find the frequency of the Casualty in Red Corridor states and in Jammu and Kashmir ?Here Frequency is (Total Casualty/Total Number of a year)
Print frequency as integer value.
Note:Red Corridor state includes Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh. Here Casualty=Killed +Wounded.Don't fill the nan value present in Killed and Wounded feature.

In [141]:
import pandas as pd
import numpy as np
df = pd.read_csv('terrorismData.csv')

year = len(set(df['Year']))

df = df[df.Country == 'India']
df['Casualty'] = df['Killed'] + df['Wounded']

jk = df[df.State == 'Jammu and Kashmir']
rc = df[(df.State == 'Jharkhand') | (df.State == 'Odisha') | (df.State == 'Andhra Pradesh') | (df.State == 'Chhattisgarh')]

jkc = int(np.sum(jk['Casualty']))
rcc = int(np.sum(rc['Casualty']))

print(rcc//year,jkc//year)

115 261